<a href="https://colab.research.google.com/github/Sunnik-Chatterjee/AP-Lab/blob/main/2328052_Lab_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Matrix multiplication and time comparison

In [1]:
import time
import numpy as np

A = [[i for i in range(100)] for j in range(100)]
B = [[i for i in range(100)] for j in range(100)]

start = time.time()
C = [[0]*100 for _ in range(100)]
for i in range(100):
    for j in range(100):
        for k in range(100):
            C[i][j] += A[i][k]*B[k][j]
end = time.time()
print("List Time:", end-start)

A1 = np.array(A)
B1 = np.array(B)

start = time.time()
C1 = np.dot(A1,B1)
end = time.time()
print("NumPy Time:", end-start)

List Time: 0.23860883712768555
NumPy Time: 0.0014050006866455078


Q2. 2D NumPy Array Operations

In [2]:
import numpy as np
a = np.random.randint(1,101,size=(10,5))
print(a)

print(np.sum(a[a%2!=0]))
print(np.sum(a[a%2==0]))
print(np.trace(a))
print(a.T)
print(a[1:6])
a[1:6] = -a[1:6]
print(a)
print(a[1:6].reshape(-1))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.sort(a.reshape(-1)))

[[73 23 73  9 60]
 [15 11 76 26 60]
 [23 85 59 11 70]
 [85 61 53 89 47]
 [35 52 36 80 37]
 [79 71 64 25 68]
 [24 18 35 24 40]
 [27 18 41 34  9]
 [28 78 26 92 62]
 [55 32  5 87 16]]
1223
1084
269
[[73 15 23 85 35 79 24 27 28 55]
 [23 11 85 61 52 71 18 18 78 32]
 [73 76 59 53 36 64 35 41 26  5]
 [ 9 26 11 89 80 25 24 34 92 87]
 [60 60 70 47 37 68 40  9 62 16]]
[[15 11 76 26 60]
 [23 85 59 11 70]
 [85 61 53 89 47]
 [35 52 36 80 37]
 [79 71 64 25 68]]
[[ 73  23  73   9  60]
 [-15 -11 -76 -26 -60]
 [-23 -85 -59 -11 -70]
 [-85 -61 -53 -89 -47]
 [-35 -52 -36 -80 -37]
 [-79 -71 -64 -25 -68]
 [ 24  18  35  24  40]
 [ 27  18  41  34   9]
 [ 28  78  26  92  62]
 [ 55  32   5  87  16]]
[-15 -11 -76 -26 -60 -23 -85 -59 -11 -70 -85 -61 -53 -89 -47 -35 -52 -36
 -80 -37 -79 -71 -64 -25 -68]
-329
-6.58
-3.0
52.32326060176296
[-89 -85 -85 -80 -79 -76 -71 -70 -68 -64 -61 -60 -59 -53 -52 -47 -37 -36
 -35 -26 -25 -23 -15 -11 -11   5   9   9  16  18  18  23  24  24  26  27
  28  32  34  35  40  41  55  60  

Q3. Class for 2D array operations

In [3]:
class Array2D:
    def __init__(self,a):
        self.a=a
    def row_reverse(self):
        return [row[::-1] for row in self.a]
    def col_reverse(self):
        return self.a[::-1]
    def both_reverse(self):
        return [row[::-1] for row in self.a[::-1]]
    def cut_border(self):
        return [row[1:-1] for row in self.a[1:-1]]

a = Array2D([[1,2,3],[4,5,6],[7,8,9]])
print(a.row_reverse())
print(a.col_reverse())
print(a.both_reverse())
print(a.cut_border())

[[3, 2, 1], [6, 5, 4], [9, 8, 7]]
[[7, 8, 9], [4, 5, 6], [1, 2, 3]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]
[[5]]


Q4. Solve linear equations using inverse

In [5]:
import numpy as np

# (i)
A1 = np.array([[1,2],[2,4]])
B1 = np.array([-4,-8])

if np.linalg.det(A1)==0:
    print("System (i): Singular Matrix → Infinite Solutions")
else:
    X1 = np.linalg.solve(A1,B1)
    print("System (i) Solution:", X1)

# (ii)
A2 = np.array([[1,2,3],[2,-3,2],[3,1,-1]])
B2 = np.array([6,14,-2])

X2 = np.linalg.solve(A2,B2)
print("System (ii) Solution:", X2)


System (i): Singular Matrix → Infinite Solutions
System (ii) Solution: [ 1. -2.  3.]


Q5) Create a 10×10 NumPy array with 1s on perimeter and 0s inside.

In [1]:
import numpy as np
a = np.zeros((10,10),int)
a[0,:]=1
a[-1,:]=1
a[:,0]=1
a[:,-1]=1
print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Q6) Write a function to flatten a 2D array into 1D array without using flatten() or ravel().

In [6]:
def flat(a):
    b=[]
    for i in a:
        for j in i:
            b.append(j)
    return b

print(flat([[1,2],[3,4]]))

[1, 2, 3, 4]


Q7) Implement a python function to reverse the rows of a 2D array in-place.

In [7]:
a = [[1,2,3],[4,5,6]]
a.reverse()
print(a)

[[4, 5, 6], [1, 2, 3]]


Q8) Create a checkerboard pattern (8×8) using NumPy arrays.

In [2]:
import numpy as np
a = np.indices((8,8)).sum(axis=0)%2
print(a)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q9) Create a 3D array (3×3×3) and slice to obtain a 2D array containing the middle row of each 2D subarray.

In [8]:
import numpy as np
a = np.arange(27).reshape(3,3,3)
print(a[:,1,:])

[[ 3  4  5]
 [12 13 14]
 [21 22 23]]


Q10) Given two arrays A and B, find common elements without using loops.

In [9]:
import numpy as np
A = np.array([1,2,3,4])
B = np.array([3,4,5,6])
print(np.intersect1d(A,B))

[3 4]
